name: Java CI

on: [push]

jobs:
  package:
      name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          java_version: ['8', '11']
          os: [ubuntu-latest]

      steps:
      - uses: actions/checkout@v1
      - name: Use Java ${{ matrix.java_version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
